#!/usr/bin/env bash

# Agentic Toolkit - Project Initialization Script

set -e

PROJECT_NAME=${1:-"my-agentic-project"}

echo "🤖 Agentic Toolkit - Project Initialization"
echo "=========================================="
echo "Project Name: $PROJECT_NAME"
echo ""

# Create project directory
if [ -d "$PROJECT_NAME" ]; then
    echo "❌ Directory '$PROJECT_NAME' already exists!"
    exit 1
fi

echo "📁 Creating project directory..."
mkdir -p "$PROJECT_NAME"
cd "$PROJECT_NAME"

# Initialize git repository
echo "🔧 Initializing Git repository..."
git init

# Create basic project structure
echo "🏗️ Creating project structure..."
mkdir -p src/{api,components,pages,utils,types}
mkdir -p tests/{unit,integration,e2e}
mkdir -p docs
mkdir -p scripts

# Create package.json
echo "📦 Creating package.json..."
cat > package.json << EOF
{
  "name": "$PROJECT_NAME",
  "version": "1.0.0",
  "description": "Agentic project initialized with Agentic Toolkit",
  "main": "src/index.js",
  "scripts": {
    "dev": "node src/index.js",
    "test": "jest",
    "build": "echo 'Build script placeholder'",
    "start": "node src/index.js"
  },
  "keywords": ["agentic", "ai", "automation"],
  "author": "Generated by Agentic Toolkit",
  "license": "MIT",
  "devDependencies": {
    "jest": "^29.0.0"
  }
}
EOF

# Create basic .gitignore
echo "📝 Creating .gitignore..."
cat > .gitignore << EOF
node_modules/
npm-debug.log*
.env
.DS_Store
*.log
dist/
build/
coverage/
EOF

# Create basic README
echo "📖 Creating README.md..."
cat > README.md << EOF
# $PROJECT_NAME

Generated by Agentic Toolkit v2.0

## Getting Started

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Start development:
   \`\`\`bash
   npm run dev
   \`\`\`

3. Run tests:
   \`\`\`bash
   npm test
   \`\`\`

## Project Structure

- \`src/\` - Source code
- \`tests/\` - Test files
- \`docs/\` - Documentation
- \`scripts/\` - Utility scripts

## Next Steps

Use Agentic Toolkit to plan and execute your development tasks:

\`\`\`bash
agentic plan
agentic next
agentic analyze
\`\`\`
EOF

# Create basic source file
echo "💻 Creating basic source file..."
cat > src/index.js << EOF
// $PROJECT_NAME - Main Entry Point
// Generated by Agentic Toolkit

console.log('🚀 $PROJECT_NAME is running!');
console.log('🤖 Powered by Agentic Toolkit v2.0');

// TODO: Implement your application logic here
EOF

# Create plan.md template
echo "📋 Creating plan.md template..."
cat > plan.md << EOF
# Project Plan: $PROJECT_NAME

## Overview
Brief description of your project goals and objectives.

## Features
- [ ] Feature 1
- [ ] Feature 2
- [ ] Feature 3

## Technical Requirements
- [ ] Backend setup
- [ ] Frontend development
- [ ] Database design
- [ ] Testing implementation

## Success Criteria
- [ ] All features implemented
- [ ] Tests passing
- [ ] Documentation complete
- [ ] Production deployment
EOF

# Initialize with git
echo "🔄 Making initial commit..."
git add .
git commit -m "Initial commit: Project initialized with Agentic Toolkit v2.0"

echo ""
echo "✅ Project '$PROJECT_NAME' initialized successfully!"
echo ""
echo "📂 Project structure created:"
echo "   ├── src/           # Source code"
echo "   ├── tests/         # Test files"
echo "   ├── docs/          # Documentation"
echo "   ├── scripts/       # Utility scripts"
echo "   ├── package.json   # Project configuration"
echo "   ├── README.md      # Project documentation"
echo "   └── plan.md        # Project planning template"
echo ""
echo "🚀 Next steps:"
echo "   cd $PROJECT_NAME"
echo "   agentic plan    # Generate tasks from plan.md"
echo "   agentic next    # Get next task to work on"
echo "   npm install     # Install dependencies"
echo "   npm run dev     # Start development"
echo ""
echo "🤖 Happy coding with Agentic Toolkit!"
